/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AutoLayout {
        "gap": string;
        "height": string;
        "padding": string;
        "paddingBottom": string;
        "paddingHorizontal": string;
        "paddingLeft": string;
        "paddingRight": string;
        "paddingTop": string;
        "paddingVertical": string;
        "width": string;
    }
}
declare global {
    interface HTMLAutoLayoutElement extends Components.AutoLayout, HTMLStencilElement {
    }
    var HTMLAutoLayoutElement: {
        prototype: HTMLAutoLayoutElement;
        new (): HTMLAutoLayoutElement;
    };
    interface HTMLElementTagNameMap {
        "auto-layout": HTMLAutoLayoutElement;
    }
}
declare namespace LocalJSX {
    interface AutoLayout {
        "gap"?: string;
        "height"?: string;
        "padding"?: string;
        "paddingBottom"?: string;
        "paddingHorizontal"?: string;
        "paddingLeft"?: string;
        "paddingRight"?: string;
        "paddingTop"?: string;
        "paddingVertical"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "auto-layout": AutoLayout;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auto-layout": LocalJSX.AutoLayout & JSXBase.HTMLAttributes<HTMLAutoLayoutElement>;
        }
    }
}
